language: java

sudo: false

jdk:
  - openjdk8

script:
  - mvn cobertura:cobertura coveralls:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report