name: CI on macos-latest
on:
  push:
    branches: [ main, development, tests_fixes ]
  pull_request:
    branches: [ main ]
jobs:
  test-on-macos:
    runs-on: macos-latest
    strategy:
      matrix:
      name: Tests with Java version = ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Silent install main project
        run: mvn --batch-mode --no-transfer-progress install
      - name: Run automation with latest ngrok-spring-boot-starter version on test-app
        working-directory: ./.github/test-app/
        run: mvn --batch-mode --no-transfer-progress test
