name: automation tests
on:
  push:
    branches: [ main, development, tests_fixes ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build & test main project
        run: mvn install
      - name: execute automation tests
        working-directory: ./.github/test-app/
        run: mvn --batch-mode --no-transfer-progress test
